# Generated by Django 4.2.30 on 2026-06-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='candles.candle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
