# Generated by Django 4.2.30 on 2026-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0002_alter_candle_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='season',
            field=models.CharField(choices=[('spring', 'Весенние'), ('summer', 'Летние'), ('holiday', 'Праздничные')], db_index=True, default='spring', max_length=20),
        ),
    ]
